import os

NAME_DIR_FILE = '../data'
NAME_FILE = 'customer_data.csv'
NAME_MODEL_DIR = '../checkpoint'

PROJECT_DIR = os.path.abspath(os.getcwd())
DATA_DIR = os.path.join(PROJECT_DIR, NAME_DIR_FILE)
CHECKPOINT_DIR = os.path.join(PROJECT_DIR, NAME_MODEL_DIR)

NAME_DATA_TYPE_COL = 'DATA_TYPE'
ID_COL = 'POLICY_ID'
NAME_COL_RENEWED = 'POLICY_IS_RENEWED'
NAME_COL_GENDER = 'INSURER_GENDER'
COL_YEARS_RENEWED = 'POLICY_YEARS_RENEWED_N'

MAX_YEARS_RENEWED_LEVEL = 4

DEL_COLUMN = [
    'POLICY_BEGIN_MONTH',
    'POLICY_SALES_CHANNEL',
    'VEHICLE_MAKE',
    'VEHICLE_MODEL',
    'VEHICLE_ENGINE_POWER',
    'POLICY_INTERMEDIARY',
    'CLAIM_AVG_ACC_ST_PRD',
    'CLIENT_REGISTRATION_REGION'
]

COLUMN_ONE_HOT = [
    'POLICY_END_MONTH',
    'POLICY_SALES_CHANNEL_GROUP',
    'POLICY_BRANCH',
    'INSURER_GENDER',
    'POLICY_CLM_N',
    'POLICY_CLM_GLT_N',
    'POLICY_PRV_CLM_N',
    'POLICY_PRV_CLM_GLT_N',
    'POLICY_YEARS_RENEWED_N'
]

DATA_TYPE = ['TRAIN', 'TEST ']
POLICY_CLM_GLT_N = ['GLT_N', 'CLM_N']
ELEM_NaN = 'N'